/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proj.rsacryptosystem;

import java.awt.Color;
import java.awt.Component;
import java.awt.font.NumericShaper.Range;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import org.apache.poi.hwpf.HWPFDocument;
import org.apache.poi.hwpf.extractor.WordExtractor;
import org.apache.poi.hwpf.usermodel.CharacterRun;
import org.apache.poi.hwpf.usermodel.Paragraph;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.openxml4j.opc.OPCPackage;
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

/**
 *
 * @author caoth
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        this.btnNhapFileBanRo.setEnabled(false);
        this.btnMaHoa.setEnabled(false);
        this.btnChuyen.setEnabled(false);
        this.btnLuuFileBanMa.setEnabled(false);
        this.btnNhapFileBanMa.setEnabled(false);
        this.btnGiaiMa.setEnabled(false);
        this.btnLuuBanRo.setEnabled(false);
    }
    
    private AlgorithmRSA rsa = new AlgorithmRSA();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        KeyGeneratePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbKichThuoc = new javax.swing.JComboBox<>();
        btnSinhKhoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtq = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtb = new javax.swing.JTextField();
        btnTaoKhoa = new javax.swing.JButton();
        EncryptPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNhapBanRo = new javax.swing.JTextArea();
        btnNhapFileBanRo = new javax.swing.JButton();
        btnMaHoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtXuatBanMa = new javax.swing.JTextArea();
        btnChuyen = new javax.swing.JButton();
        btnLuuFileBanMa = new javax.swing.JButton();
        DecryptPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNhapBanMa = new javax.swing.JTextArea();
        btnNhapFileBanMa = new javax.swing.JButton();
        btnGiaiMa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtXuatBanRo = new javax.swing.JTextArea();
        btnLuuBanRo = new javax.swing.JButton();
        btnTaoMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mã hoá RSA");
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1000, 900));
        setSize(new java.awt.Dimension(1000, 900));
        getContentPane().setLayout(null);

        ContentPanel.setBackground(new java.awt.Color(51, 255, 204));
        ContentPanel.setMinimumSize(new java.awt.Dimension(1000, 900));
        ContentPanel.setPreferredSize(new java.awt.Dimension(1000, 900));
        ContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TitleLabel.setText("MÃ HOÁ RSA");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ContentPanel.add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        KeyGeneratePanel.setBackground(new java.awt.Color(204, 255, 204));
        KeyGeneratePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sinh khoá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        KeyGeneratePanel.setMinimumSize(new java.awt.Dimension(900, 180));
        KeyGeneratePanel.setPreferredSize(new java.awt.Dimension(900, 180));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Kích thước khoá");

        cmbKichThuoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbKichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "256", "512", "1024", "2048", "3072" }));

        btnSinhKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSinhKhoa.setText("Sinh khoá tự động");
        btnSinhKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhKhoaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("p");

        txtp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("q");

        txtq.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("a");

        txta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("b");

        txtb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnTaoKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTaoKhoa.setText("Tạo khoá");
        btnTaoKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoKhoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KeyGeneratePanelLayout = new javax.swing.GroupLayout(KeyGeneratePanel);
        KeyGeneratePanel.setLayout(KeyGeneratePanelLayout);
        KeyGeneratePanelLayout.setHorizontalGroup(
            KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeyGeneratePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(KeyGeneratePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtp))
                    .addGroup(KeyGeneratePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cmbKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSinhKhoa))
                    .addGroup(KeyGeneratePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtq)))
                .addGap(18, 18, 18)
                .addGroup(KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txta, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(txtb))
                .addContainerGap())
            .addGroup(KeyGeneratePanelLayout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(btnTaoKhoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KeyGeneratePanelLayout.setVerticalGroup(
            KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeyGeneratePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinhKhoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeyGeneratePanelLayout.createSequentialGroup()
                        .addGroup(KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KeyGeneratePanelLayout.createSequentialGroup()
                        .addGroup(KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KeyGeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaoKhoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContentPanel.add(KeyGeneratePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 900, 200));

        EncryptPanel.setBackground(new java.awt.Color(255, 204, 204));
        EncryptPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã hoá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        EncryptPanel.setPreferredSize(new java.awt.Dimension(420, 460));
        EncryptPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bản rõ");
        EncryptPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNhapBanRo.setColumns(20);
        txtNhapBanRo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNhapBanRo.setLineWrap(true);
        txtNhapBanRo.setRows(5);
        jScrollPane1.setViewportView(txtNhapBanRo);

        EncryptPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 240, 150));

        btnNhapFileBanRo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNhapFileBanRo.setText("File");
        btnNhapFileBanRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapFileBanRoActionPerformed(evt);
            }
        });
        EncryptPanel.add(btnNhapFileBanRo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        btnMaHoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMaHoa.setText("Mã hoá");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaActionPerformed(evt);
            }
        });
        EncryptPanel.add(btnMaHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Bản mã");
        EncryptPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtXuatBanMa.setColumns(20);
        txtXuatBanMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtXuatBanMa.setLineWrap(true);
        txtXuatBanMa.setRows(5);
        jScrollPane2.setViewportView(txtXuatBanMa);

        EncryptPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 240, 160));

        btnChuyen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChuyen.setText("Chuyển");
        btnChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenActionPerformed(evt);
            }
        });
        EncryptPanel.add(btnChuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        btnLuuFileBanMa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLuuFileBanMa.setText("Lưu");
        btnLuuFileBanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileBanMaActionPerformed(evt);
            }
        });
        EncryptPanel.add(btnLuuFileBanMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        ContentPanel.add(EncryptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 320, 420, 460));

        DecryptPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giải mã", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        DecryptPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Bản mã");
        DecryptPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNhapBanMa.setColumns(20);
        txtNhapBanMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNhapBanMa.setLineWrap(true);
        txtNhapBanMa.setRows(5);
        jScrollPane3.setViewportView(txtNhapBanMa);

        DecryptPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 240, 150));

        btnNhapFileBanMa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNhapFileBanMa.setText("File");
        btnNhapFileBanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapFileBanMaActionPerformed(evt);
            }
        });
        DecryptPanel.add(btnNhapFileBanMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        btnGiaiMa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGiaiMa.setText("Giải mã");
        btnGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMaActionPerformed(evt);
            }
        });
        DecryptPanel.add(btnGiaiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Bản rõ");
        DecryptPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtXuatBanRo.setColumns(20);
        txtXuatBanRo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtXuatBanRo.setLineWrap(true);
        txtXuatBanRo.setRows(5);
        jScrollPane4.setViewportView(txtXuatBanRo);

        DecryptPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 240, 160));

        btnLuuBanRo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLuuBanRo.setText("Lưu");
        btnLuuBanRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuBanRoActionPerformed(evt);
            }
        });
        DecryptPanel.add(btnLuuBanRo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        ContentPanel.add(DecryptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 420, 460));

        btnTaoMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });
        ContentPanel.add(btnTaoMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 800, -1, -1));

        getContentPane().add(ContentPanel);
        ContentPanel.setBounds(0, 0, 1000, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        // TODO add your handling code here:
        this.cmbKichThuoc.setSelectedIndex(0);
        this.txtp.setText("");
        this.txtq.setText("");
        this.txta.setText("");
        this.txtb.setText("");
        this.btnNhapFileBanRo.setEnabled(false);
        this.btnMaHoa.setEnabled(false);
        this.btnChuyen.setEnabled(false);
        this.btnLuuFileBanMa.setEnabled(false);
        this.btnNhapFileBanMa.setEnabled(false);
        this.btnGiaiMa.setEnabled(false);
        this.btnLuuBanRo.setEnabled(false);
        this.txtNhapBanMa.setText("");
        this.txtNhapBanRo.setText("");
        this.txtXuatBanMa.setText("");
        this.txtXuatBanRo.setText("");
    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void btnChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenActionPerformed
        // TODO add your handling code here:
        String banMa = this.txtXuatBanMa.getText();
        if(banMa.equals("")){
            JOptionPane.showMessageDialog(ContentPanel, "Chuyển bản mã thất bại, bản mã không được rỗng!");
        }else{
            this.txtNhapBanMa.setText(banMa);
            JOptionPane.showMessageDialog(ContentPanel, "Chuyển bản mã thành công!");
        }
    }//GEN-LAST:event_btnChuyenActionPerformed

    private void btnSinhKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhKhoaActionPerformed
        // TODO add your handling code here:
        int bits = Integer.parseInt((String) cmbKichThuoc.getSelectedItem());
        rsa.taoKhoa(bits);
        this.txtp.setText(rsa.getP().toString());
        this.txtq.setText(rsa.getQ().toString());
        this.txta.setText(rsa.getA().toString());
        this.txtb.setText(rsa.getB().toString());
        JOptionPane.showMessageDialog(ContentPanel, "Tạo khoá thành công!");
        this.btnNhapFileBanRo.setEnabled(true);
        this.btnMaHoa.setEnabled(true);
        this.btnNhapFileBanMa.setEnabled(true);
        this.btnGiaiMa.setEnabled(true);
    }//GEN-LAST:event_btnSinhKhoaActionPerformed

    private void btnTaoKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoKhoaActionPerformed
        // TODO add your handling code here:
        String p = txtp.getText();
        String q = txtq.getText();
        String a = txta.getText();
        String b = txtb.getText();
        System.out.println(b);
        if(p.equals("")){
            JOptionPane.showMessageDialog(ContentPanel, "Chưa nhập số nguyên tố p");
        }
        if(q.equals("")){
            JOptionPane.showMessageDialog(ContentPanel, "Chưa nhập số nguyên tố q");
        }
        if(b.equals("")){
            JOptionPane.showMessageDialog(ContentPanel, "Chưa nhập số nguyên tố b");
        }
        rsa.taoKhoa(new BigInteger(p), new BigInteger(q), new BigInteger(b));
        this.txta.setText(rsa.getA().toString());
        JOptionPane.showMessageDialog(ContentPanel, "Tạo khoá thành công!");
        this.btnNhapFileBanRo.setEnabled(true);
        this.btnMaHoa.setEnabled(true);
        this.btnNhapFileBanMa.setEnabled(true);
        this.btnGiaiMa.setEnabled(true);
    }//GEN-LAST:event_btnTaoKhoaActionPerformed
    public static BigInteger cipher;
    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaActionPerformed
        // TODO add your handling code here:
        String plaintText = this.txtNhapBanRo.getText();
        System.out.println("Bản rõ: " + plaintText);
        if(plaintText.equals("")){
            JOptionPane.showMessageDialog(ContentPanel, "Mã hoá không thành công, bản rõ không được để trống!");
        }else{
            String cipherText = rsa.encrypt(plaintText);
            System.out.println("Bản mã sau khi mã hoá: " + cipherText);
            this.txtXuatBanMa.setText(cipherText);
            JOptionPane.showMessageDialog(ContentPanel, "Mã hoá thành công!");
            this.btnChuyen.setEnabled(true);
            this.btnLuuFileBanMa.setEnabled(true);
        }
    }//GEN-LAST:event_btnMaHoaActionPerformed

    private void btnGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiMaActionPerformed
        // TODO add your handling code here:
        String cipherText = this.txtNhapBanMa.getText();
        System.out.println("Bản mã: " + cipherText);
        if(cipherText.equals("")){
            JOptionPane.showMessageDialog(ContentPanel, "Giải mã không thành công, bản mã không được để trống!");
        }else{
            String plaintText = rsa.decrypt(cipherText);
            System.out.println("Bản rõ sau khi giải mã: " + plaintText);
            this.txtXuatBanRo.setText(plaintText);
            JOptionPane.showMessageDialog(ContentPanel, "Giải mã thành công!");
            this.btnLuuBanRo.setEnabled(true);
        }
    }//GEN-LAST:event_btnGiaiMaActionPerformed

    private void btnNhapFileBanRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapFileBanRoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("D:/"));
        int result = fileChooser.showDialog(this, "Tải file bản rõ");
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                String content = docFile(selectedFile);
                this.txtNhapBanRo.setText(content);
            } catch (IOException ex) {
                Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidFormatException ex) {
                Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnNhapFileBanRoActionPerformed

    private void btnNhapFileBanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapFileBanMaActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("D:/"));
        int result = fileChooser.showDialog(this, "Tải file bản mã");
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                String content = docFile(selectedFile);
                this.txtNhapBanMa.setText(content);
            } catch (IOException ex) {
                Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidFormatException ex) {
                Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnNhapFileBanMaActionPerformed

    private void btnLuuFileBanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileBanMaActionPerformed
        try {
            // TODO add your handling code here:
            luuFile(this.txtXuatBanMa.getText());
        } catch (IOException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidFormatException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuFileBanMaActionPerformed

    private void btnLuuBanRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuBanRoActionPerformed
        try {
            // TODO add your handling code here:
            luuFile(this.txtXuatBanRo.getText());
        } catch (IOException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidFormatException ex) {
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuBanRoActionPerformed

    private static String docFile(File file) throws IOException, FileNotFoundException, InvalidFormatException {
        String filePath = file.getAbsolutePath();
        String content = "";
        if (filePath.endsWith(".txt")) {
            content = docFileTxt(file);
        } else if (filePath.endsWith(".doc")) {
            content = docFileDoc(file);
        }else if(filePath.endsWith(".docx")){
            content = docFileDocx(file);
        }
        return content;
    }
    
    private static String docFileTxt(File file) {
        StringBuilder content = new StringBuilder();
        try (BufferedReader br = new BufferedReader(new FileReader(file, StandardCharsets.UTF_8))) {
            String line;
            while ((line = br.readLine()) != null) {
                content.append(line).append("\n");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return content.toString().trim();
    }
    
    public static String docFileDoc(File file) {
        StringBuilder content = new StringBuilder();
		try {
			FileInputStream fis = new FileInputStream(file);

			HWPFDocument doc = new HWPFDocument(fis);

			WordExtractor we = new WordExtractor(doc);

			String[] paragraphs = we.getParagraphText();
			
//			System.out.println("Total no of paragraph "+paragraphs.length);
			for (String para : paragraphs) {
                            content.append(para.toString());
//				System.out.println(para.toString());
			}
			fis.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
                return content.toString();
	}
    
    public static String docFileDocx(File file) throws FileNotFoundException, IOException{
        try (FileInputStream fis = new FileInputStream(file)) {
            XWPFDocument document = new XWPFDocument(fis);
            StringBuilder content = new StringBuilder();
            for (XWPFParagraph paragraph : document.getParagraphs()) {
                content.append(paragraph.getText()).append("\n");
            }
            return content.toString();
        }
    }
    
    private void luuFile(String content) throws IOException, InvalidFormatException {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("D:/"));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String fileName = file.getName();
            if (fileName.endsWith(".doc")) {
                luuFileDoc(file, content);
            }else if(fileName.endsWith(".docx")) {
                luuFileDocx(content, file);
            }
            else if (fileName.endsWith(".txt")) {
                luuFileTxt(file, content);
            } else {
                // Handle unsupported file types
                JOptionPane.showMessageDialog(this, "Phầm mềm không hỗ trợ loại file này, vui lòng chọn file .doc or .txt file.");
            }
        }
    }

    private void luuFileDoc(File file, String content) {
        try (FileOutputStream fos = new FileOutputStream(file);
             BufferedOutputStream bos = new BufferedOutputStream(fos)) {
            bos.write(content.getBytes());
            JOptionPane.showMessageDialog(this, "Lưu file thành công!.");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lưu file thất bại!");
        }
    }

    private void luuFileTxt(File file, String content) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            writer.write(content);
            JOptionPane.showMessageDialog(this, "Lưu file thành công!");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lưu file thất bại!");
        }
    }

    private void luuFileDocx(String content, File file) {
        XWPFDocument document = new XWPFDocument();
        XWPFParagraph paragraph = document.createParagraph();
        paragraph.createRun().setText(content);
        try (FileOutputStream fos = new FileOutputStream(file)) {
            document.write(fos);
            JOptionPane.showMessageDialog(this, "Lưu file thành công!");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Lưu file thất bại!");
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lưu file thất bại!");
            Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel DecryptPanel;
    private javax.swing.JPanel EncryptPanel;
    private javax.swing.JPanel KeyGeneratePanel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton btnChuyen;
    private javax.swing.JButton btnGiaiMa;
    private javax.swing.JButton btnLuuBanRo;
    private javax.swing.JButton btnLuuFileBanMa;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JButton btnNhapFileBanMa;
    private javax.swing.JButton btnNhapFileBanRo;
    private javax.swing.JButton btnSinhKhoa;
    private javax.swing.JButton btnTaoKhoa;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JComboBox<String> cmbKichThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtNhapBanMa;
    private javax.swing.JTextArea txtNhapBanRo;
    private javax.swing.JTextArea txtXuatBanMa;
    private javax.swing.JTextArea txtXuatBanRo;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txtb;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtq;
    // End of variables declaration//GEN-END:variables
}
